### ISSUE TITLE
Download stuck at 99%

### ISSUE THREAD

**Issue by Toylerrr** [mjishnu/pypdl#20] opened 2024-06-09 16:26 UTC
I'm trying to use this package to download a files from a [Gamevault server](https://github.com/Phalcode/gamevault-backend). This is the API [endpoint ](https://demo.gamevau.lt/api/docs#/game/getGameDownload) that I am using. The auth seems to work and it will download the file segments but once it hits 99% it halts and just sits there. 

```
from pypdl import *
from aiohttp import BasicAuth
import logging

logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger()

def main():
    # Using Basic Authentication
    username = "test"
    password = "asdfghjkl"
    headers = {"User-Agent":"My cool Program/0.1"}
    auth = BasicAuth(username, password)
    print(f"Auth object: {auth}")
    dl = Pypdl(auth=auth, headers=headers)
    # Start the download
    dl.start(url='http://192.168.0.200:5006/api/games/1/download', multisegment=True, block=True)

if __name__ == '__main__':
    main()
```

would you happen to have any insight on how I can get this to work?

**Comment by mjishnu** [comment] 2024-06-13 14:44
hey, does this occur when its trying to combine the files, can you check the download folder and see the size of each file if all have same size it means its an issue in the combining process

**Comment by Toylerrr** [comment] 2024-06-13 16:37
yes it does seem to have downloaded all the chunks then sits at 99%

**Comment by mjishnu** [comment] 2024-06-13 16:41
will look into it. did you try again and faced same issue ?

**Comment by Toylerrr** [comment] 2024-06-13 17:06
Interestingly enough if I do a non-multi segment download it does complete but doesn't give me the files just the JSON as a zip and says 401 error. Password is guaranteed correct.

`{
  "message": "Unauthorized",
  "statusCode": 401
}`

**Comment by mjishnu** [comment] 2024-06-13 17:12
> Interestingly enough if I do a non-multi segment download it does complete but doesn't give me the files just the JSON as a zip and says 401 error. Password is guaranteed correct.
> 
> `{
>   "message": "Unauthorized",
>   "statusCode": 401
> }`

this is certainly weird if password was correct. what about size is it displaying any and you are passing it as [aiohttp.basicauth](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.BasicAuth) right

**Comment by mjishnu** [comment] 2024-06-13 17:17
> Fresh try this AM after a server restart to see if that was the issue. Still sitting at 99%. Just a note I was troubleshooting a lot when I posted originally and I couldn't get it to work with gamevault. 
> 
> ![image](https://github.com/mjishnu/pypdl/assets/4400902/0a0fb416-7918-4e59-9335-54afedc32fd9)
> 

ah now that i am looking, try and change name to something without whitespace that could be causing the combination not occur, try to set name to something like "booth" or something anything without white spaces. currently i ama a bit busy i will try to reproduce it tomorrow sorry for the delay.

**Comment by mjishnu** [comment] 2024-06-16 19:51
with commit https://github.com/mjishnu/pypdl/commit/700ba23e50005db8325ebe021e5c06c135723157 the issue regarding Unauthorized status while using single segment download has been fixed, it was caused by a typo 

the issue regarding download stuck at 99% this is because of incorrect segment size which is caused due the a [bug in Gamevault server](https://github.com/Phalcode/gamevault-backend/blob/a70119c6127ba7471ddb6485526b48e8705447ba/src/modules/files/files.service.ts#L673). it was accepting non-inclusive range headers this is not a standarad practice as range headers should be [inclusive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) 

i have opened an issue regarding this in Gamevault repo: https://github.com/Phalcode/gamevault-backend/issues/298

**Comment by Toylerrr** [comment] 2024-06-17 18:24
Thank you, this is something that I never would have figured out. I greatly appreciate your assistance and look forward to this fix on the pypdl as well as your fix on the gamevault repo.

**Comment by mjishnu** [comment] 2024-06-18 09:34
Thanks for reporting, with [v1.4.1](https://github.com/mjishnu/pypdl/releases/tag/1.4.1) this should be fixed.

**Closed by mjishnu** 2024-06-18 09:34 UTC
Labels: bug
